version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - err113
    - errcheck
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - funcorder
    - ginkgolinter
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - iface
    - inamedparam
    - importas
    - ineffassign
    - intrange
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    cyclop:
      max-complexity: 15
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    generated: lax
    rules:
      - linters:
          - nolintlint
        path: cmd/main.go
      - linters:
          - lll
        path: api/*
      - linters:
          - ireturn
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
